import time
from time import sleep
import sys
import os
clear = lambda: os.system('cls')
clear()
from pygame._sdl2 import *
from pygame import mixer

mixer.init(devicename='Hoofdtelefoon (JBL LIVE400BT Stereo)') #run de audio.py in cmd voor uw huidige audiodevice

def play(mp3, volume):
	sound = mixer.Sound(mp3)
	sound.play()
	sound.set_volume(volume)

def write(text, speed):
	for x in text:
		print(x, end='')
		sys.stdout.flush()
		sound = mixer.Sound("blop.mp3")
		sound.play()
		sound.set_volume(0.7)
		sleep(speed)
	print("\n")

def write2(text, speed):
	for x in text:
		print(x, end='')
		sys.stdout.flush()
		sound = mixer.Sound("blop2.mp3")
		sound.play()
		sound.set_volume(0.7)
		sleep(speed)
	print("\n")

def write3(text, speed):
	for x in text:
		print(x, end='')
		sys.stdout.flush()
		sound = mixer.Sound("blop3.mp3")
		sound.play()
		sound.set_volume(0.2)
		sleep(speed)
	print("\n")

clear()
check1 = False
while check1:
	write3("This is a school project made by Joost Robat!", 0.08)
	time.sleep(0.5)
	write3("Be sure to enjoy this adventure and that you've followed the instructions for your sound effects for the full experience...", 0.08)
	time.sleep(0.5)
	write3("Enjoy...", 0.2)
	time.sleep(1)
	clear()
	time.sleep(1)
	play("1.mp3", 0.5)
	write("You're in a land with no name...", 0.06)
	time.sleep(2.5)
	write("Who am I?", 0.1)
	time.sleep(0.5)
	write("Where am I?", 0.1)
	time.sleep(1.5)
	clear()
	time.sleep(0.5)
	write("Suddenly you remember...", 0.06)
	time.sleep(1.5)
	write("Your name is:\n", 0.08)
	name = input()
	time.sleep(1)
	write("That's right your name is " + name + "...", 0.08)
	time.sleep(1.5)
	clear()
	write("You were walking back from work when you got hit on the back of your head...", 0.06)
	time.sleep(1.5)
	write("The land you're in is known for war...", 0.06)
	time.sleep(1.5)
	write("Only war...", 0.2)
	time.sleep(2)
	clear()
	time.sleep(2)
	write("You're blinded and can't see a thing...", 0.06)
	time.sleep(1.5)
	write("You should've made that deal with that smuggler...", 0.1)
	time.sleep(1.5)
	write("I need to find an escape...", 0.06)
	time.sleep(1.5)
	write("I've got limited choices but I have to work with what I have...", 0.06)
	time.sleep(2.5)
	clear()
	write("Your blindfold is loosely tied, and should come off easily...", 0.04)
	time.sleep(2)
	write("You shake your head furiously and the room is revealed while your blindfold slowly slides down...", 0.06)
	time.sleep(3)
	clear()
	write("There are three obvious choices that you can make right now...", 0.06)
	time.sleep(1.5)
	write("There's a C4 explosive in the room you're in...", 0.06)
	time.sleep(1)
	write("It's in kicking distance, but you don't know if it's been tempered with...", 0.06)
	time.sleep(1.5)
	write("There are a few bottles to your right, you don't know what they contain...", 0.08)
	time.sleep(1.5)
	write("Lastly there's the option to try and wringle your hands out the ropes that have tied them...", 0.06)
	time.sleep(2)
	write("Alright calm down and think...", 0.1)
	time.sleep(1)
	write("Which one do I choose: 1, 2 or 3?", 0.1)
	check1 = False
q1checkpoint = True
while q1checkpoint:
	q1 = input()
	if q1 == "1":
		clear()
		time.sleep(1)
		write("As you unleash your anger in a kick movement towards the C4 explosive it flies across the room against the wall", 0.06)
		time.sleep(3)
		write("Nothing happend...", 0.1)
		time.sleep(2)
		write("Alright to be honest I don't know what I was expe-", 0.04)
		write("BOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOM!!!!!", 0.01)
		time.sleep(0.5)
		write("The explosive flings you across the room against the wall leaving you injured with heavy bleeding wounds...", 0.08)
		time.sleep(2)
		write("You slowly lose sight and bleed out...", 0.15)
		time.sleep(1)
		write("You died...", 0.2)
		loop1 = True
		while loop1:
			loop1 = input("Restart? Yes/No\n")
			if loop1 == "Yes" or q2 == "yes":
				check1 = True
				loop1 = False
				continue
			if loop1 == "No" or q2 == "no":
				pass
			else:
				write("That's not a valid response you potato!", 0.04)
				continue
	if q1 == "2":
		clear()
		time.sleep(1.5)
		write("You grab one of the bottles with your feet but drop it while carrying...", 0.06)
		play("break.mp3", 0.1)
		time.sleep(1.5)
		write("The bottles left shards of sharp glass on the floor, while you try to pick one up and succeed your foot gets cut...", 0.08)
		time.sleep(1.5)
		write("You throw The shard of glass on your lap and from there onto the side of the chair...", 0.08)
		time.sleep(2)
		write("You try to grab the glass with your hands...", 0.08)
		time.sleep(2)
		write("You manage to cut the rope around your hands with the glass you obtained...", 0.08)
		time.sleep(0.5)
		write("You slowly cut the rope aroud your legs and freely move them...", 0.08)
		time.sleep(1)
		clear()
		time.sleep(0.5)
		write("You walk towards the door in the room wondering what's on the other side...", 0.08)
		time.sleep(1)
		write("You slowly open the door...", 0.08)
		play("opening.mp3", 0.3)
		time.sleep(3)
		time.sleep(0.5)
		write("You find yourself at a set of stairs which follow to a door...", 0.08)
		time.sleep(1)
		clear()
		time.sleep(0.5)
		write("You are greeted by the bright and warming smile of the sun...", 0.08)
		time.sleep(2)
		write("You've never felt happier being greeted by the sun in this hot forsaken country...", 0.08)
		time.sleep(2)
		write("After you realize that you have regained your freedom you start running...", 0.06)
		time.sleep(1.5)
		write("There aren't many things going through your head...", 0.06)
		time.sleep(1.5)
		write("Where am I going? You ask yourself...", 0.08)
		time.sleep(2)
		write("You spot a road which you recognise...", 0.08)
		time.sleep(1)
		play("running.mp3", 0.3)
		write("This road leads you home!", 0.06)
		time.sleep(2)
		write("As you run over de road you can see nothing but suddenly over the horizon your house appears...", 0.08)
		time.sleep(2)
		write("There! There it is!", 0.06)
		time.sleep(0.5)
		write("As you near your house your excitement grows...", 0.1)
		time.sleep(1)
		write("Keep running! Keep Running!", 0.06)
		time.sleep(0.5)
		write("Almost there Im coming 💣♓♍♒♋♏●📪 ❖♋■♏⬧⬧♋📪 ♋■■♏!", 0.06)
		time.sleep(1.5)
		write("Your legs almost can't keep up the speed as you sprint towards your goal...", 0.08)
		time.sleep(1)
		write("I should join a sprinting competition sometime...", 0.08)
		time.sleep(1)
		write("Why is it so silent...", 0.08)
		time.sleep(1)
		write("Normally their so noisy...", 0.08)
		time.sleep(1)
#Trippy effect <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
		play("static.mp3", 0.1)
		clear()
		print("✋❍ ⬧□❒❒⍓📬📬📬")
		time.sleep(0.25)
		clear()
		print("Im sorry...")
		time.sleep(0.3)
		clear()
		print("✋❍ ⬧□❒❒⍓📬📬📬")
		time.sleep(0.4)
		clear()
		play("static.mp3", 0.1)
		print("Im sorry...")
		time.sleep(0.6)
		clear()
		print("✋❍ ⬧□❒❒⍓📬📬📬")
		time.sleep(0.2)
		clear()
		play("static.mp3", 0.1)
		print("Im sorry...")
		time.sleep(0.3)
		clear()
		print("✋❍ ⬧□❒❒⍓📬📬📬")
		time.sleep(0.09)
		clear()
		print("Im sorry...")
		time.sleep(0.08)
		clear()
		print("✋❍ ⬧□❒❒⍓📬📬📬")
		time.sleep(0.07)
		clear()
		print("Im sorry")
		time.sleep(0.06)
		clear()
		print("✋❍ ⬧□❒❒⍓📬📬📬")
		time.sleep(0.05)
		clear()
		print("Im sorry...")
		time.sleep(0.04)
		clear()
		print("✋❍ ⬧□❒❒⍓📬📬📬")
		time.sleep(0.03)
		clear()
		print("Im sorry...")
		time.sleep(0.02)
		clear()
		print("✋❍ ⬧□❒❒⍓📬📬📬")
		time.sleep(0.01)
		clear()
		play("static.mp3", 0.1)
		print("Im sorry")
		clear()
		print("✋❍ ⬧□❒❒⍓📬📬📬")
		time.sleep(0.2)
		clear()
		play("static.mp3", 0.1)
		print("Im sorry...")
		time.sleep(0.3)
		clear()
		print("✋❍ ⬧□❒❒⍓📬📬📬")
		time.sleep(0.09)
		clear()
		print("Im sorry...")
		time.sleep(0.08)
		clear()
		print("✋❍ ⬧□❒❒⍓📬📬📬")
		time.sleep(0.07)
		clear()
		print("Im sorry")
		time.sleep(0.06)
		clear()
		print("✋❍ ⬧□❒❒⍓📬📬📬")
		time.sleep(0.05)
		clear()
		print("Im sorry...")
		time.sleep(0.04)
		clear()
		print("✋❍ ⬧□❒❒⍓📬📬📬")
		time.sleep(0.03)
		clear()
		print("Im sorry")
		time.sleep(0.5)
		clear()
		time.sleep(2)
		write("You gently open the door...", 0.1)
		play("opening.mp3", 0.3)
		time.sleep(3)
		clear()
		write("Hello, is anyone home?", 0.1)
		time.sleep(0.5)
		clear()
		play("damage.mp3", 0.5)
		time.sleep(0.05)
		play("damage.mp3", 0.5)
		time.sleep(0.05)
		play("damage.mp3", 0.5)
		time.sleep(1)
		play("premonition.mp3", 0.5)
		write("What happend...", 0.2)
		time.sleep(2)
		write("They're... They're...", 0.2)
		time.sleep(0.5)
		write("Dead...", 0.4)
		time.sleep(2)
		write("Why would... Would... Anyone do this...", 0.1)
		time.sleep(2)
		write("Your mind is wiped...", 0.08)
		time.sleep(1)
		write("You can see your mother and father lumped over against the wall...", 0.08)
		time.sleep(2)
		write("You walk over and feel their pulse praying for their lives...", 0.08)
		time.sleep(1)
		write("Your father is dead...", 0.1)
		time.sleep(1)
		write("Your mother is dead...", 0.1)
		time.sleep(1)
		write("Your sister is no where to be found...", 0.08)
		time.sleep(1)
		write("You run up to her room but she's not there...", 0.08)
		time.sleep(1)
		write("You check your parents room...", 0.08)
		time.sleep(1)
		clear()
		time.sleep(1)
		write("Shocked you wipe your mind of any thoughts...", 0.08)
		time.sleep(2)
		write("There is nothing left for me...", 0.08)
		time.sleep(1)
		write("Perhaps I should just flee...", 0.08)
		time.sleep(1)
		write("You look at the house which is left in shambles...", 0.08)
		time.sleep(2)
		write("Everything is broken...", 0.08)
		time.sleep(1)
		write("Just like I am right now...", 0.08)
		time.sleep(2)
		write("I should make a choice...", 0.06)
		time.sleep(1)
		write("I can salvage and check for any usefull stuff left", 0.08)
		time.sleep(1)
		write("Or I can flee right now, because they might be looking for me...", 0.08)
		time.sleep(1)
		clear()
		write("What do I choose 1 or 2?\n", 0.08)
		q3 = input()
		if q3 == "1":
			time.sleep(1)
			clear()
			time.sleep(1)
			write("Right, I should flee...", 0.08)
			time.sleep(1)
			write("They're probably after me...", 0.08)
			time.sleep(1)
			play("running.mp3", 0.2)
			write("Where do I go from here...", 0.08)
			time.sleep(1)
			play("busyindianstreet.mp3", 0.5)
			write("I need food...", 0.08)
			time.sleep(1)
			write("I'll steal some from the market...", 0.08)
			time.sleep(1)
			write("As you run towards the busy side of the village it starts to become more and more crowded...", 0.08)
			time.sleep(1)
			clear()
			time.sleep(1)
			write("You put on the hoodie from your jacket so people don't recognise you...", 0.08)
			time.sleep(1)
			write("As you run by a fruit market you grab a few apples and run faster...")
			time.sleep(1)
			write("A total of 3 isn't much...", 0.08)
			time.sleep(1)
			write("You keep jogging along softly...", 0.08)
			time.sleep(1)
			write("I've sinned in so many ways now...", 0.08)
			time.sleep(1)
			write("Forgive me lord...", 0.08)
			time.sleep(1)
			write("As you jog along you sot a scooter with keys...", 0.08)
			time.sleep(1)
			write("I know it's a sin but I have to....", 0.08)
			time.sleep(1)
			write("You hop on the scooter and quickly turn on the motor...", 0.08)
			time.sleep(1)
			write("You have never driven a scooter yet the ride continues smoothly...", 0.08)
			time.sleep(1)
			write("You keep driving and as you go faster the busy part of the village fades...", 0.08)
			time.sleep(1)
			clear()
			time.sleep(1)
			write("Hours passed...", 0.15)
			time.sleep(1)
			write("I'm so tired...", 0.2)
			time.sleep(1)
			write("As your vehicle slows down you come to a stop...", 0.08)
			time.sleep(1)
			write("")
		if q3 == "1":
			time.sleep(1)
			clear()
			time.sleep(1)
			write("You carefully look through your stuff, but everything of use has dissapeared...", 0.1)
			time.sleep(1)
			write("Your old shelves are lying on the floor...", 0.08)
			time.sleep(1)
			write("You remember having stored a knife somewhere, yet its a vague memory...", 0.08)
			time.sleep(1)
			write("Perhaps your mom stored it away with your old toys...", 0.08)
			time.sleep(1.5)
			write("You open one of the three boxes stored under your bed...", 0.08)
			time.sleep(1)
			write("The boxes are still untouched since the day that you stored them...", 0.08)
			time.sleep(1)
			write("The box doesn't contain the pocket knife...", 0.08)
			time.sleep(1)
			write("You turn it upside down and everything drops out of the box...", 0.08)
			time.sleep(1)
			write("You search under the toys and find the pocket knife in the old dusty toys...", 0.08)
			time.sleep(1)
			write("You decide to skip the room of your parents and your sister and go straight to the storage room...", 0.08)
			time.sleep(1)
			write("When you where a kid you found the storage room scary...", 0.08)
			time.sleep(1)
			write("It was the place where guests slept whenever we had some over...", 0.08)
			time.sleep(1)
			clear()
			time.sleep(1)
			play("opening.mp3", 0.5)
			time.sleep(1)
			write("Just as scary as before...", 0.08)
			time.sleep(1)
			write("You open the few boxes on the ground next to the closet while staring at the family pictures on a shelf...", 0.08)
			time.sleep(1)
			write("stop it " + name + " don't get emotional, it's not the time for that...", 0.08)
			time.sleep(1)
			write("The boxes don't contain very much usefull items...", 0.08)
			time.sleep(1)
			write("You decide to check the kitchen...", 0.08)
			time.sleep(1)
			clear()
			time.sleep(1)
			write("You walk down the stairs and enter the kitchen...", 0.08)
			time.sleep(1)
			write("I took way too long upstairs I need to hurry up...", 0.08)
			time.sleep(1)
			write("You quickly start scavenging the kitchen", 0.08)
			time.sleep(1)
			write("You find a few lunch bars, these are very high in proteïn and compact to carry...", 0.08)
			time.sleep(1)
			write("There are a total of 6 bars, which you all throw into your jackets pocket...", 0.08)
			time.sleep(1)
			write("You close the zipper of your jacket put your pocket knife in your pocket and go out the back door...", 0.08)
			play("busyindianstreet.mp3", 0.6)
			time.sleep(1)
			write("I need to calm down...", 0.08)
			time.sleep(0.5)
			write("Don't walk fast just relax...", 0.08)
			time.sleep(1)
			write("You have entered the busy side of the village...", 0.08)
			time.sleep(1)
			write("All these small markets... all these people, yet I don't have any money...", 0.08)
			time.sleep(0.5)
			write("Any family....", 0.08)
			time.sleep(0.5)
			write("Any roof...", 0.08)
			time.sleep(1)
			write("Suddenly you spot someone out of the corner of your eye...", 0.08)
			time.sleep(0.5)
			write("Someone you recongnise...", 0.08)
			time.sleep(0.5)
			write("You can't really make out who that is so you focus your sight on him...", 0.08)
			time.sleep(0.5)
			write("It's the smuggler...", 0.08)
			time.sleep(1)
			write("Do I approach him? or do I leave him be and find my own way of leaving this forsaken country?", 0.08)
			time.sleep(1)
			write("Make a choice...", 0.08)
			q4 = input("1 or 2")
			if q4 == "1":
				write("You approach the man from before and ask if you could speak with him again...", 0.08)
				time.sleep(1)
				write2("Yes we can talk at my place...", 0.08)
				time.sleep(1)
				write("You follow him home, even though you know it's risky...", 0.08)
				time.sleep(1)
				write("You approach a nice looking house, where the two of you enter at the front...", 0.08)
				time.sleep(1.5)
				write2("Come on in, I haven't had guests in a while...", 0.08)
				time.sleep(1)
				play("dooropen2.mp3", 0.5)
				clear()
				time.sleep(1.5)
				write("Thanks for having me...", 0.08)
				time.sleep(1)
				write2("No problem you, but you look like you've seen a ghost...", 0.08)
				time.sleep(0.5)
				write2("What happend?", 0.08)
				time.sleep(2)
				write("...", 0.4)
				time.sleep(1)
				write("They're dead...", 0.08)
				time.sleep(1)
				write2("Who are?", 0.08)
				time.sleep(1)
				play("static.mp3", 0.3)
				write("💣♓♍♒♋♏●📪 ❖♋■♏⬧⬧♋📪 ♋■■♏", 0.04)
				time.sleep(1)
				write2("Im assuming your related to them?", 0.08)
				time.sleep(1)
				write("You knew them?", 0.08)
				time.sleep(1)
				write2("Spoke to them once at the market...", 0.08)
				time.sleep(1)
				write("You still in the smuggling business?", 0.08)
				time.sleep(1)
				write2("Are you interested?", 0.08)
				time.sleep(1)
				write("I am but I can't offer you any money...", 0.08)
				time.sleep(1)
				write2("Then I can't do anything for you man...", 0.08)
				time.sleep(1)
				write("Can I atleast stay the night here?", 0.08)
				time.sleep(1)
				write2("Why's that...", 0.08)
				time.sleep(1)
				write("The gang that killed them is probably after me...", 0.08)
				time.sleep(1)
				play("static.mp3", 0.3)
				write2("💣♓♍♒♋♏●📪 ❖♋■♏⬧⬧♋📪 ♋■■♏?", 0.04)
				time.sleep(1)
				write("You nod...", 0.08)
				time.sleep(1)
				write2("Fine, but 1 night thats all...", 0.08)
				time.sleep(1)
				clear()
				write("Can you give me a tour? You ask...", 0.08)
				time.sleep(1)
				write2("No I'll only show you your room...", 0.08)
				time.sleep(1)
				write("Fine...", 0.08)
				time.sleep(1)
				write2("Know that I am only doing this because I've had some laughs with 💣♓♍♒♋♏●📪...", 0.08)
				time.sleep(1)
				write2("I have to go out so I'll show you your room...", 0.08)
				time.sleep(1)
				write2("Follow me...", 0.08)
				play("heartbeat.mp3", 0.5)
				time.sleep(1)
				write("Wait...", 0.08)
				time.sleep(1)
				write("I have the money...", 0.08)
				time.sleep(1)
				write2("Show me then...", 0.08)
				time.sleep(1)
				write("Why did I say that!?", 0.06)
				time.sleep(1.5)
				write("It's at my place I just have to go get it!", 0.06)
				time.sleep(1.5)
				write2("Riiiiiiiight...", 0.15)
				time.sleep(1)
				write("Promise me if I really get the money because you won't belive me you'll give me a discount...", 0.08)
				time.sleep(1)
				write2("Sure whatever you want...", 0.08)
				time.sleep(1)
				write("I'll go now to get the money...", 0.08)
				time.sleep(1)
				write2("Riiiiight...", 0.2)
				time.sleep(0.5)
				write2("The money...", 0.2)
				time.sleep(1)
				play("busyindianstreet.mp3", 1)
				clear()
				time.sleep(1)
				write("You walk back to the market towards your house...", 0.08)
				time.sleep(1)
				write("This is my only chance for money...", 0.08)
				time.sleep(1)
				write("There has to be some money left there...", 0.08)
				time.sleep(0.5)
				write("Suddenly a voice grabs your attention...", 0.08)
				time.sleep(1)
				write3("You look like one don't ya...", 0.08)
				time.sleep(1)
				write("You look to your left where you see someone with a hoodie and backpack...", 0.08)
				time.sleep(1)
				write3("Come here...", 0.08)
				time.sleep(1)
				write("All your instincts tell you to walk the other way...", 0.08)
				time.sleep(0.5)
				write("Yet you refuse...", 0.08)
				time.sleep(1)
				write("You walk towards the suspicious man...", 0.08)
				time.sleep(0.5)
				write("He's rather small, you could easily take him in a fight...", 0.08)
				time.sleep(1)
				write("That's right...", 0.08)
				time.sleep(0.5)
				write("I steal from him...", 0.08)
				time.sleep(1)
				write3("You wanna buy some pills?", 0.08)
				time.sleep(1)
				write("What do you have?", 0.08)
				time.sleep(1)
				write("You see him reach into his pocket for a pair of white pills....", 0.08)
				time.sleep(0.5)
				write("What is that...", 0.08)
				time.sleep(1)
				write3("You don't do MDMA?", 0.08)
				time.sleep(0.5)
				write3("Sorry wrong fellow then I'll keep looking for some potential buyers...", 0.08)
				time.sleep(1)
				write("I do use MDMA...", 0.08)
				time.sleep(1)
				clear()
				time.sleep(1)
				write("...", 0.08)
				time.sleep(0.5)
				write("Why did I say that!?", 0.08)
				time.sleep(1)
				write3("Alright then now we're talking! Wanna buy?", 0.06)
				time.sleep(1.5)
				write("I'm looking for some more adventure if you know what I mean....", 0.08)
				time.sleep(1)
				write("What do you have in your backpack...", 0.08)
				play("heartbeat.mp3", 0.5)
				time.sleep(1)
				write3("Let me grab some for ya...", 0.08)
				time.sleep(0.5)
				write("QUICK NOW KNOCK HIM OUT!", 0.06)
				time.sleep(1)
				write("You grab the first thing you see and...", 0.08)
				play("break.mp3", 0.5)
				write("Knocked out...", 0.08)
				time.sleep(1)
				write("Your heart beats fast", 0.08)
				time.sleep(1)
				write("Your reach into the opposite pocket which he pulled the MDMA from...", 0.08)
				time.sleep(0.5)
				write("Bingo...", 0.04)
				time.sleep(1)
				write("You pull out your hand containing a stack of money...", 0.08)
				time.sleep(0.5)
				write("About 500 bucks", 0.08)
				time.sleep(1)
				write("There's now way thats enough...", 0.08)
				time.sleep(1)
				write("I'll have to negotiate my way out of this mess...", 0.08)
				time.sleep(0.5)
				write("Let's first get out of here, before he wakes up...", 0.08)
				time.sleep(1)
				play("running.mp3", 0.5)
				write("As you run you see th never ending crowd of people...", 0.08)
				time.sleep(1)
				write("I gotta go back to the house I'll just wing it with this money and hope that he takes it...", 0.08)
				time.sleep(1)
				write("The amount of people decrease over time and you've slowed down to a jogging tempo..", 0.08)
				time.sleep(1)
				write("As you spot the smuggler's house over the horizon you hear a voice behind you calling...", 0.08)
				time.sleep(1)
				write2(name + "?", 0.08)
				time.sleep(1)
				write("You turn around and spot the smuggler standing behind you...", 0.08)
				time.sleep(1)
				write("Hey, I didn't see you... Uhhh What's your name again?", 0.08)
				time.sleep(1)
				write2("Mohammed...", 0.08)
				time.sleep(0.5)
				write2("Why are you in such a hurry...", 0.08)
				time.sleep(0.5)
				write("Ok stay calm...", 0.08)
				time.sleep(0.5)
				write("I just went for a quick jog to my home and back for the money...", 0.08)
				time.sleep(1)
				write("You reach into your pocket and show him the money...", 0.08)
				time.sleep(1)
				write2("Let me see how much that is...", 0.08)
				time.sleep(0.5)
				write("He reaches out to grab it and you pull back your hand as a reflex...", 0.08)
				time.sleep(0.5)
				write("We had a deal that I'd get a discount", 0.08)
				time.sleep(1)
				write2("Yeah I hoped you wouldn't have brought that up...", 0.08)
				time.sleep(1)
				write("While the conversation continues you pull out a lunch bar and start munching it down...", 0.08)
				time.sleep(1)
				write2("That looked like a good stack of money I'll do it for all of that...", 0.08)
				time.sleep(1)
				write("He took the bait without hesitating...", 0.08)
				time.sleep(0.5)
				write("Sure, you got yourself a deal...", 0.08)
				time.sleep(1)
				write("You hand over the money and as he counts it you see the regret in his face...", 0.08)
				time.sleep(1)
				write2("Well, it's a good thing that I already had another a trip planned", 0.08)
				time.sleep(1)
				write("When are we going?You ask him...", 0.08)
				time.sleep(1)
				write2("This evening, we had a change of plans because my other client wasn't happy with me extending the waiting time...", 0.08)
				time.sleep(0.5)
				write2("So your just riding along, lucky you...", 0.08)
				time.sleep(1)
				write("You nod while trying to hide your excitement...", 0.08)
				time.sleep(1)
				clear()
				time.sleep(1)
				print("Two hours have passed since the deal...")
				time.sleep(2)
				write2("Wake up...", 0.08)
				time.sleep(0.5)
				write2("Hey...", 0.08)
				time.sleep(1)
				write2("Wake up!", 0.06)
				time.sleep(1)
				write("Huh?", 0.1)
				time.sleep(1)
				write("Are we leaving?", 0.1)
				time.sleep(1)
				write2("Yeah, we are...", 0.08)
				time.sleep(1)
				write("But I'm so tired...", 0.08)
				time.sleep(1)
				write2("I'll lead you to the van you can sleep there too we'll leave in 10 minutes...", 0.08)
				time.sleep(1)
				write("As you the smuggler guide's you via the backdoor to the van you get greeted by a windy rainy outside world...", 0.08)
				time.sleep(1)
				write("The smuggler opens the van and helps you in, after that you fall asleep...", 0.08)
				time.sleep(1)
				clear()
				time.sleep(1)
				play("car_ride.mp3", 0.5)
	if q1 == "3":
		clear()
		time.sleep(1.5)
		write("As you desperatly try to wringle your hands out of the rope which tie them together you hurt yourself...", 0.06)
		time.sleep(1.5)
		write("You have been angered by the frustration of trying to free yourself of this rope...", 0.06)
		time.sleep(1)
		write("As your frustration grows, so does your agression...", 0.08)
		time.sleep(1)
		write("You start flicking your arms around which produces quite some noise...", 0.08)
		time.sleep(1)
		write("You free yourself from the rope and untie the rope around your legs and stand up to admire the room you're in...", 0.06)
		time.sleep(1)
		write("You walk to a set of stairs which you spot, but as you walk there you hear people shouting some stuff in a weird language...", 0.06)
		time.sleep(2)
		write("Standing in the open doorway you decide to move...", 0.06)
		time.sleep(2)
		write("This is bad you can hear them getting closer...", 0.06)
		time.sleep(1)
		write("The talking stopped, but there is still someone there you just know it...", 0.06)
		time.sleep(1.5)
		clear()
		time.sleep(1)
		play("keys.mp3", 0.3)
		write("You hear the rattling of the keys...", 0.06)
		time.sleep(1)
		write("This is bad I need to hide...", 0.06)
		time.sleep(0.5)
		write("You crawl under a desk desperate for a good hiding spot and desperate that he won't spot you...", 0.08)
		time.sleep(0.5)
		play("footsteps.mp3", 0.3)
		time.sleep(3)
		write("As you hear him walking down the stairs you just faced your heartbeat begins to speed up...", 0.06)
		play("heartbeat.mp3", 0.4)
		play("gun_cock.mp3", 0.4)
		time.sleep(1.5)
		write("If he finds you now its game over and you know it...", 0.08)
		time.sleep(1)
		write("As your high heartbeat continues you don't know what to do...", 0.08)
		time.sleep(1)
		write("He dissapeared from your sights and you don't see anything...", 0.08)
		play("gunshot.mp3", 0.4)
		time.sleep(2)
		write("Before you even can process what happend you see blood and feel a pain in your leg...", 0.08)
		time.sleep(1)
		write("There you are you scum!", 0.05)
		time.sleep(0.5)
		write("As the man who just fired his gun kicks the desk you are once again revealed to the room...", 0.08)
		time.sleep(1)
		play("gunshot.mp3", 0.4)
		write("As the man points his gun at you he right after pulls the trigger...", 0.1)
		time.sleep(1)
		write("You died...", 0.2)
		loop2 = True
		while loop2:
			loop2q = input("Restart? Yes/No\n")
			if loop2q == "Yes" or loop2q == "yes":
				break
				check1 = True
				continue
			if loop2q == "No" or loop2q == "no":
				break
			else:
				write("That's not a valid response you potato!", 0.04)
				continue
	else:
		write("That's not a valid answer you potato!", 0.04)
		continue
